insert into public.teams (name, code, flag_url, group_letter, is_tbd)
values
  ('Canada', 'CAN', 'https://flagcdn.com/w80/ca.png', 'A', false),
  ('Mexico', 'MEX', 'https://flagcdn.com/w80/mx.png', 'A', false),
  ('United States', 'USA', 'https://flagcdn.com/w80/us.png', 'A', false),
  ('Costa Rica', 'CRC', 'https://flagcdn.com/w80/cr.png', 'A', false),
  ('Argentina', 'ARG', 'https://flagcdn.com/w80/ar.png', 'B', false),
  ('Chile', 'CHL', 'https://flagcdn.com/w80/cl.png', 'B', false),
  ('Peru', 'PER', 'https://flagcdn.com/w80/pe.png', 'B', false),
  ('Venezuela', 'VEN', 'https://flagcdn.com/w80/ve.png', 'B', false),
  ('Brazil', 'BRA', 'https://flagcdn.com/w80/br.png', 'C', false),
  ('Colombia', 'COL', 'https://flagcdn.com/w80/co.png', 'C', false),
  ('Ecuador', 'ECU', 'https://flagcdn.com/w80/ec.png', 'C', false),
  ('Paraguay', 'PRY', 'https://flagcdn.com/w80/py.png', 'C', false),
  ('France', 'FRA', 'https://flagcdn.com/w80/fr.png', 'D', false),
  ('Germany', 'DEU', 'https://flagcdn.com/w80/de.png', 'D', false),
  ('Netherlands', 'NLD', 'https://flagcdn.com/w80/nl.png', 'D', false),
  ('Switzerland', 'CHE', 'https://flagcdn.com/w80/ch.png', 'D', false),
  ('Spain', 'ESP', 'https://flagcdn.com/w80/es.png', 'E', false),
  ('Portugal', 'PRT', 'https://flagcdn.com/w80/pt.png', 'E', false),
  ('Croatia', 'HRV', 'https://flagcdn.com/w80/hr.png', 'E', false),
  ('Serbia', 'SRB', 'https://flagcdn.com/w80/rs.png', 'E', false),
  ('Belgium', 'BEL', 'https://flagcdn.com/w80/be.png', 'F', false),
  ('Denmark', 'DNK', 'https://flagcdn.com/w80/dk.png', 'F', false),
  ('Sweden', 'SWE', 'https://flagcdn.com/w80/se.png', 'F', false),
  ('Poland', 'POL', 'https://flagcdn.com/w80/pl.png', 'F', false),
  ('Morocco', 'MAR', 'https://flagcdn.com/w80/ma.png', 'G', false),
  ('Senegal', 'SEN', 'https://flagcdn.com/w80/sn.png', 'G', false),
  ('Nigeria', 'NGA', 'https://flagcdn.com/w80/ng.png', 'G', false),
  ('Ghana', 'GHA', 'https://flagcdn.com/w80/gh.png', 'G', false),
  ('Japan', 'JPN', 'https://flagcdn.com/w80/jp.png', 'H', false),
  ('South Korea', 'KOR', 'https://flagcdn.com/w80/kr.png', 'H', false),
  ('Australia', 'AUS', 'https://flagcdn.com/w80/au.png', 'H', false),
  ('Iran', 'IRN', 'https://flagcdn.com/w80/ir.png', 'H', false),
  ('Uruguay', 'URY', 'https://flagcdn.com/w80/uy.png', 'I', false),
  ('Czech Republic', 'CZE', 'https://flagcdn.com/w80/cz.png', 'I', false),
  ('Ukraine', 'UKR', 'https://flagcdn.com/w80/ua.png', 'I', false),
  ('Turkey', 'TUR', 'https://flagcdn.com/w80/tr.png', 'I', false),
  ('Italy', 'ITA', 'https://flagcdn.com/w80/it.png', 'J', false),
  ('Austria', 'AUT', 'https://flagcdn.com/w80/at.png', 'J', false),
  ('Norway', 'NOR', 'https://flagcdn.com/w80/no.png', 'J', false),
  ('Hungary', 'HUN', 'https://flagcdn.com/w80/hu.png', 'J', false),
  ('Ivory Coast', 'CIV', 'https://flagcdn.com/w80/ci.png', 'K', false),
  ('Cameroon', 'CMR', 'https://flagcdn.com/w80/cm.png', 'K', false),
  ('Algeria', 'DZA', 'https://flagcdn.com/w80/dz.png', 'K', false),
  ('TBD Group K Slot 4', 'TBA', null, 'K', true),
  ('New Zealand', 'NZL', 'https://flagcdn.com/w80/nz.png', 'L', false),
  ('Panama', 'PAN', 'https://flagcdn.com/w80/pa.png', 'L', false),
  ('TBD Group L Slot 3', 'TBC', null, 'L', true),
  ('TBD Group L Slot 4', 'TBD', null, 'L', true)
on conflict (code) do update
set
  name = excluded.name,
  flag_url = excluded.flag_url,
  group_letter = excluded.group_letter,
  is_tbd = excluded.is_tbd;
