insert into public.teams (name, code, group_letter, is_tbd)
values
  ('Canada', 'CAN', 'A', false),
  ('Mexico', 'MEX', 'A', false),
  ('United States', 'USA', 'A', false),
  ('Costa Rica', 'CRC', 'A', false),
  ('Argentina', 'ARG', 'B', false),
  ('Chile', 'CHL', 'B', false),
  ('Peru', 'PER', 'B', false),
  ('Venezuela', 'VEN', 'B', false),
  ('Brazil', 'BRA', 'C', false),
  ('Colombia', 'COL', 'C', false),
  ('Ecuador', 'ECU', 'C', false),
  ('Paraguay', 'PRY', 'C', false),
  ('France', 'FRA', 'D', false),
  ('Germany', 'DEU', 'D', false),
  ('Netherlands', 'NLD', 'D', false),
  ('Switzerland', 'CHE', 'D', false),
  ('Spain', 'ESP', 'E', false),
  ('Portugal', 'PRT', 'E', false),
  ('Croatia', 'HRV', 'E', false),
  ('Serbia', 'SRB', 'E', false),
  ('Belgium', 'BEL', 'F', false),
  ('Denmark', 'DNK', 'F', false),
  ('Sweden', 'SWE', 'F', false),
  ('Poland', 'POL', 'F', false),
  ('Morocco', 'MAR', 'G', false),
  ('Senegal', 'SEN', 'G', false),
  ('Nigeria', 'NGA', 'G', false),
  ('Ghana', 'GHA', 'G', false),
  ('Japan', 'JPN', 'H', false),
  ('South Korea', 'KOR', 'H', false),
  ('Australia', 'AUS', 'H', false),
  ('Iran', 'IRN', 'H', false),
  ('Uruguay', 'URY', 'I', false),
  ('Czech Republic', 'CZE', 'I', false),
  ('Ukraine', 'UKR', 'I', false),
  ('Turkey', 'TUR', 'I', false),
  ('Italy', 'ITA', 'J', false),
  ('Austria', 'AUT', 'J', false),
  ('Norway', 'NOR', 'J', false),
  ('Hungary', 'HUN', 'J', false),
  ('Ivory Coast', 'CIV', 'K', false),
  ('Cameroon', 'CMR', 'K', false),
  ('Algeria', 'DZA', 'K', false),
  ('TBD Group K Slot 4', 'TBA', 'K', true),
  ('New Zealand', 'NZL', 'L', false),
  ('Panama', 'PAN', 'L', false),
  ('TBD Group L Slot 3', 'TBC', 'L', true),
  ('TBD Group L Slot 4', 'TBD', 'L', true)
on conflict (code) do update
set
  name = excluded.name,
  group_letter = excluded.group_letter,
  is_tbd = excluded.is_tbd,
  flag_url = excluded.flag_url;
